services:
  - type: worker
    name: urbanace-bot
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: BOT_TOKEN
        sync: false
